### ISSUE TITLE
Unwanted routes

### ISSUE THREAD

**Issue by sharona1610** [vikasgarg1/wdiproject2new#1]
The routes folder is not used as far as I can see. Also the recipes controller is not used. All the routes pertaining to recipes are included in chefs controller. Can try to change it to make it cleaner

**Comment by vikasgarg1** [comment]
I think I recreated the controllers folder yesterday when I was screwing around with some of the folders. Thanks for catching that, I've gone ahead and deleted the routes folder after testing to make sure its not linked to anything.
